export default 
{
  "login": "wesbos",
  "id": 176013,
  "node_id": "MDQ6VXNlcjE3NjAxMw==",
  "avatar_url": "https://avatars.githubusercontent.com/u/176013?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/wesbos",
  "html_url": "https://github.com/wesbos",
  "followers_url": "https://api.github.com/users/wesbos/followers",
  "following_url": "https://api.github.com/users/wesbos/following{/other_user}",
  "gists_url": "https://api.github.com/users/wesbos/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/wesbos/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/wesbos/subscriptions",
  "organizations_url": "https://api.github.com/users/wesbos/orgs",
  "repos_url": "https://api.github.com/users/wesbos/repos",
  "events_url": "https://api.github.com/users/wesbos/events{/privacy}",
  "received_events_url": "https://api.github.com/users/wesbos/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Wes Bos",
  "company": "me",
  "blog": "www.wesbos.com",
  "location": "Hamilton, Ontario",
  "email": null,
  "hireable": true,
  "bio": "I create courses that make learning things like JavaScript easy and fun 🔥",
  "twitter_username": null,
  "public_repos": 280,
  "public_gists": 58,
  "followers": 23395,
  "following": 31,
  "created_at": "2010-01-04T10:11:44Z",
  "updated_at": "2021-01-22T03:12:34Z"
}
// {
//   "login": "glittergunner9669",
//   "id": 69204913,
//   "node_id": "MDQ6VXNlcjY5MjA0OTEz",
//   "avatar_url": "https://avatars.githubusercontent.com/u/69204913?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/glittergunner9669",
//   "html_url": "https://github.com/glittergunner9669",
//   "followers_url": "https://api.github.com/users/glittergunner9669/followers",
//   "following_url": "https://api.github.com/users/glittergunner9669/following{/other_user}",
//   "gists_url": "https://api.github.com/users/glittergunner9669/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/glittergunner9669/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/glittergunner9669/subscriptions",
//   "organizations_url": "https://api.github.com/users/glittergunner9669/orgs",
//   "repos_url": "https://api.github.com/users/glittergunner9669/repos",
//   "events_url": "https://api.github.com/users/glittergunner9669/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/glittergunner9669/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": null,
//   "company": null,
//   "blog": "",
//   "location": null,
//   "email": null,
//   "hireable": null,
//   "bio": null,
//   "twitter_username": null,
//   "public_repos": 27,
//   "public_gists": 0,
//   "followers": 0,
//   "following": 0,
//   "created_at": "2020-08-04T14:04:28Z",
//   "updated_at": "2020-12-24T18:51:50Z"
// }
// {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
